baseurl: "https://www.beyondvm.com/"
languageCode: "en-us"
title: "BeyondVM"
disqusShortname: "beyondvm"
paginate: 10 # optional
copyright: "Content Copyright 2015+ Ben Thomas"
editor: "atom"
paginatePath: "page"
preservetaxonomynames: true
pygmentsuseclasses: true
MetaDataFormat: "yaml"

params:
  author: "Ben Thomas"
  disclaimer: "The views expressed anywhere on this site are strictly mine and not the position of any employer, vendor or provider including but not limited to my employer, VMware or any of its companies. Any solutions that I offer are 'use at your own risk.'"
  twitter: "wazoo" # optional
  github: "wazoo" # optional
  github_blog: "BeyondVM" # optional
  facebook: "beyondvm" # optional
  gplus: "102140179649518942198" # optional
  linkedin: "benthomas" # optional
  googleAnalyticsUserID: "Your Analytics User Id" # optional
  rss_link: "https://www.beyondvm.com/index.xml"
  pluralsight: "ben-thomas"
  copyright: "© 2015+ BeyondVM. All Rights Reserved."
  download_domain: "https://downloads.beyondvm.com"
  hosted_by: ""
  widget_about: true
  widget_social: true
  widget_search: true
  widget_disclaimer: true
  widget_sponsors: false
  widget_topics: true
  widget_tags: true
  widget_twitter: true
  widget_recient_comments: true
  tapir_token: ""
  tapir_secret: ""

permalinks:
  post: "/:year/:month/:slug/" # optional
  page: "/:title/"

taxonomies:
    tag: "tags"
    topic: "topics"
    series: "series"
    project: "projects"
    certificaton: "certifications"
    guide: "guides"
    sponsor: "sponsors"
